packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@swc/core': set this to true or false
  esbuild: true
  node-pty: set this to true or false
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - "@tailwindcss/oxide"
  - better-sqlite3
  - node-pty

verifyDepsBeforeRun: false
